path = r'c:\Users\Jos jr\Documents\PlatformIO\Projects\NFC4\src\ntag424_handler.cpp'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = 'bool NTAG424Handler::writeNDEF(const String& url) {'
end_marker = 'bool NTAG424Handler::selectApplication(const uint8_t* aid) {'
start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print('ERROR: could not find function boundaries')
    exit(1)

new_func = (
    'bool NTAG424Handler::writeNDEF(const String& url) {\n'
    '    // Write a minimal NDEF URI record to NTAG424 NDEF file (File No 0x02, ISO EF E104).\n'
    '    //\n'
    '    // SECURITY CONTEXT NOTE:\n'
    '    //   AuthenticateEV2First establishes a *DESFire native* session (CLA=0x90).\n'
    '    //   ISO 7816 ISOUpdateBinary (CLA=0x00) uses a separate security context and\n'
    '    //   the card correctly rejects it with SW=6982 (Security Status Not Satisfied).\n'
    '    //   Solution: use native DESFire WriteData (CLA=90 INS=8D) which runs inside\n'
    '    //   the active DESFire auth session. No ISO SELECT FILE is needed since the\n'
    '    //   file is identified by FileNo=0x02 directly in the WriteData command.\n'
    '    //\n'
    '    // NFC Forum Type 4 Tag NDEF file format (raw NDEF, no TLV wrapper):\n'
    '    //   Bytes 0-1:  NLEN  (big-endian uint16) = byte length of the NDEF message\n'
    '    //   Bytes 2..:  NDEF message (raw NDEF records - NOT TLV-wrapped like Type 2 Tag)\n'
    '    //\n'
    '    // NDEF URI Well-known record (Short Record SR=1):\n'
    '    //   0xD1  flags (MB=1 ME=1 CF=0 SR=1 IL=0 TNF=1 Well-known)\n'
    '    //   0x01  type_length = 1\n'
    '    //   ??    payload_length = 1(uri_id) + url_body_len\n'
    "    //   'U'   type (0x55)\n"
    '    //   0x04  URI identifier (0x04=https://, 0x03=http://, 0x00=no abbreviation)\n'
    '    //   ...   URL body (scheme prefix removed)\n'
    '    //\n'
    '    // WriteData success response: SW1=0x91 SW2=0x00\n'
    '\n'
    '    // Normalise scheme to lower-case for matching\n'
    '    String urlLower = url;\n'
    '    urlLower.toLowerCase();\n'
    '\n'
    '    String shortUrl = url;\n'
    '    uint8_t uriIdentifier = 0x00;  // no abbreviation (fallback)\n'
    '    if (urlLower.startsWith("https://")) {\n'
    '        shortUrl = url.substring(8);\n'
    '        uriIdentifier = 0x04;\n'
    '    } else if (urlLower.startsWith("http://")) {\n'
    '        shortUrl = url.substring(7);\n'
    '        uriIdentifier = 0x03;\n'
    '    }\n'
    '\n'
    '    uint8_t shortLen = (uint8_t)shortUrl.length();\n'
    '    if (shortLen > 220) {\n'
    '        logError("NDEF URL too long (max ~220 chars)");\n'
    '        return false;\n'
    '    }\n'
    '\n'
    '    // NDEF record bytes:\n'
    '    //   header(3): 0xD1 + typeLen_field(1) + payloadLen_field(1)\n'
    "    //   type(1):   'U'\n"
    '    //   payload:   uriIdentifier(1) + url_body(shortLen)\n'
    '    uint8_t payloadLen = 1 + shortLen;          // uriId + url body\n'
    '    uint8_t recordLen  = 3 + 1 + payloadLen;    // header(3) + type(1) + payload\n'
    '    uint16_t nlen      = (uint16_t)recordLen;   // NLEN = size of the single NDEF record\n'
    '\n'
    '    // Build raw NDEF file content (written at file offset 0)\n'
    '    uint8_t buf[256];\n'
    '    size_t pos = 0;\n'
    '\n'
    '    // 2-byte NLEN (big-endian)\n'
    '    buf[pos++] = (uint8_t)((nlen >> 8) & 0xFF);\n'
    '    buf[pos++] = (uint8_t)(nlen & 0xFF);\n'
    '\n'
    '    // NDEF URI record\n'
    '    buf[pos++] = 0xD1;          // MB=1 ME=1 CF=0 SR=1 IL=0 TNF=001 (Well-known)\n'
    '    buf[pos++] = 0x01;          // Type length = 1\n'
    '    buf[pos++] = payloadLen;    // Payload length = 1 + shortLen\n'
    "    buf[pos++] = 'U';           // Record type = URI (0x55)\n"
    '    buf[pos++] = uriIdentifier; // URI scheme identifier\n'
    '    memcpy(buf + pos, shortUrl.c_str(), shortLen);\n'
    '    pos += shortLen;\n'
    '\n'
    '    // Native DESFire WriteData (CLA=90 INS=8D):\n'
    '    //   Lc data = FileNo(1) | Offset(3 LE) | Length(3 LE) | FileData\n'
    '    uint8_t apdu[5 + 7 + 256];\n'
    '    apdu[0] = 0x90;               // CLA: native DESFire\n'
    '    apdu[1] = 0x8D;               // INS: WriteData\n'
    '    apdu[2] = 0x00;               // P1\n'
    '    apdu[3] = 0x00;               // P2\n'
    '    apdu[4] = (uint8_t)(7 + pos); // Lc = file params(7) + data\n'
    '    apdu[5] = 0x02;               // FileNo = 02 (NDEF file)\n'
    '    apdu[6]  = 0x00;              // Offset byte 0 (LE)\n'
    '    apdu[7]  = 0x00;              // Offset byte 1\n'
    '    apdu[8]  = 0x00;              // Offset byte 2\n'
    '    apdu[9]  = (uint8_t)(pos & 0xFF);         // Length byte 0 (LE)\n'
    '    apdu[10] = (uint8_t)((pos >> 8) & 0xFF);  // Length byte 1\n'
    '    apdu[11] = 0x00;              // Length byte 2\n'
    '    memcpy(apdu + 12, buf, pos);\n'
    '    size_t apduLen = 12 + pos;\n'
    '\n'
    '    char dbgBuf[64];\n'
    '    sprintf(dbgBuf, ">> WriteData File02 (NDEF), %u bytes (NLEN=%u)", (unsigned)pos, (unsigned)nlen);\n'
    '    logDebug(dbgBuf);\n'
    '    logToWeb("Schrijf NDEF URL naar kaart...", "info");\n'
    '\n'
    '    uint8_t response[16];\n'
    '    size_t responseLen = sizeof(response);\n'
    '    bool ok = transceiveRaw(apdu, apduLen, response, responseLen);\n'
    '    if (ok && responseLen >= 2) {\n'
    '        uint8_t sw1 = response[responseLen - 2];\n'
    '        uint8_t sw2 = response[responseLen - 1];\n'
    '        if (sw1 == 0x91 && sw2 == 0x00) {\n'
    '            logDebug("<< NDEF write OK (SW=9100)");\n'
    '            logToWeb("NDEF URL geschreven", "success");\n'
    '            return true;\n'
    '        } else {\n'
    '            char errBuf[48];\n'
    '            sprintf(errBuf, "NDEF write rejected SW=%02X%02X", sw1, sw2);\n'
    '            logError(errBuf);\n'
    '            logToWeb("NDEF URL schrijven mislukt", "error");\n'
    '            return false;\n'
    '        }\n'
    '    }\n'
    '    logError("NDEF write failed (no response)");\n'
    '    logToWeb("NDEF URL schrijven mislukt", "error");\n'
    '    return false;\n'
    '}\n'
    '\n'
)

new_content = content[:start_idx] + new_func + content[end_idx:]
with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)
print('Done. Replaced %d chars with %d chars.' % (end_idx - start_idx, len(new_func)))
