path = r'c:\Users\Jos jr\Documents\PlatformIO\Projects\NFC4\src\ntag424_handler.cpp'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = 'bool NTAG424Handler::writeNDEF(const String& url) {'
end_marker = 'bool NTAG424Handler::selectApplication(const uint8_t* aid) {'
start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print('ERROR: could not find function boundaries start=%d end=%d' % (start_idx, end_idx))
    exit(1)

new_func = (
    'bool NTAG424Handler::writeNDEF(const String& url) {\n'
    '    // Write a minimal NDEF URI record to NTAG424 NDEF file (File No 0x02, ISO EF E104).\n'
    '    //\n'
    '    // Uses sendCommand() (CLA=90, adds Le=00) which is required for native DESFire\n'
    '    // commands via ISO 7816-4 wrapping. transceiveRaw() builds the same PCB+APDU\n'
    '    // but WITHOUT the Le byte, causing SW=917E (Length Error) on WriteData.\n'
    '    //\n'
    '    // NFC Forum Type 4 Tag NDEF file format (raw NDEF, no TLV wrapper):\n'
    '    //   Bytes 0-1:  NLEN  (big-endian uint16) = byte length of the NDEF message\n'
    '    //   Bytes 2..:  NDEF message (raw NDEF records)\n'
    '    //\n'
    '    // NDEF URI Well-known record (Short Record SR=1):\n'
    '    //   0xD1  flags (MB=1 ME=1 CF=0 SR=1 IL=0 TNF=1 Well-known)\n'
    '    //   0x01  type_length = 1\n'
    '    //   ??    payload_length = 1(uri_id) + url_body_len\n'
    "    //   'U'   type (0x55)\n"
    '    //   0x04  URI identifier (0x04=https://, 0x03=http://, 0x00=no abbreviation)\n'
    '    //   ...   URL body (scheme prefix removed)\n'
    '    //\n'
    '    // sendCommand() wraps as: 90 8D 00 00 Lc [FileNo Offset(3LE) Length(3LE) data] 00\n'
    '\n'
    '    // Normalise scheme to lower-case for matching\n'
    '    String urlLower = url;\n'
    '    urlLower.toLowerCase();\n'
    '\n'
    '    String shortUrl = url;\n'
    '    uint8_t uriIdentifier = 0x00;  // no abbreviation (fallback)\n'
    '    if (urlLower.startsWith("https://")) {\n'
    '        shortUrl = url.substring(8);\n'
    '        uriIdentifier = 0x04;\n'
    '    } else if (urlLower.startsWith("http://")) {\n'
    '        shortUrl = url.substring(7);\n'
    '        uriIdentifier = 0x03;\n'
    '    }\n'
    '\n'
    '    uint8_t shortLen = (uint8_t)shortUrl.length();\n'
    '    if (shortLen > 220) {\n'
    '        logError("NDEF URL too long (max ~220 chars)");\n'
    '        return false;\n'
    '    }\n'
    '\n'
    '    // NDEF record: header(3) + type(1) + payload(1+shortLen)\n'
    '    uint8_t payloadLen = 1 + shortLen;         // uriId + url body\n'
    '    uint8_t recordLen  = 3 + 1 + payloadLen;   // 0xD1 typeLen payloadLen + type + payload\n'
    '    uint16_t nlen      = (uint16_t)recordLen;  // NLEN = size of this single NDEF record\n'
    '\n'
    '    // Build the NDEF file content (NLEN + record)\n'
    '    uint8_t fileBuf[256];\n'
    '    size_t filePos = 0;\n'
    '\n'
    '    fileBuf[filePos++] = (uint8_t)((nlen >> 8) & 0xFF); // NLEN hi\n'
    '    fileBuf[filePos++] = (uint8_t)(nlen & 0xFF);         // NLEN lo\n'
    '    fileBuf[filePos++] = 0xD1;          // MB=1 ME=1 CF=0 SR=1 IL=0 TNF=001\n'
    '    fileBuf[filePos++] = 0x01;          // Type length = 1\n'
    '    fileBuf[filePos++] = payloadLen;    // Payload length\n'
    "    fileBuf[filePos++] = 'U';           // Record type = URI\n"
    '    fileBuf[filePos++] = uriIdentifier; // URI scheme identifier\n'
    '    memcpy(fileBuf + filePos, shortUrl.c_str(), shortLen);\n'
    '    filePos += shortLen;\n'
    '\n'
    '    // Build WriteData native command (without CLA/P1/P2 - sendCommand adds those):\n'
    '    //   [INS=0x8D] [FileNo] [Offset(3 LE)] [Length(3 LE)] [FileData]\n'
    '    uint8_t cmd[1 + 7 + 256];\n'
    '    cmd[0] = 0x8D;                      // INS: WriteData\n'
    '    cmd[1] = 0x02;                      // FileNo = 02 (NDEF file)\n'
    '    cmd[2] = 0x00;                      // Offset byte 0 (LE)\n'
    '    cmd[3] = 0x00;                      // Offset byte 1\n'
    '    cmd[4] = 0x00;                      // Offset byte 2\n'
    '    cmd[5] = (uint8_t)(filePos & 0xFF);         // Length byte 0 (LE)\n'
    '    cmd[6] = (uint8_t)((filePos >> 8) & 0xFF);  // Length byte 1\n'
    '    cmd[7] = 0x00;                      // Length byte 2\n'
    '    memcpy(cmd + 8, fileBuf, filePos);\n'
    '    size_t cmdLen = 8 + filePos;        // INS(1) + params(7) + data\n'
    '\n'
    '    char dbgBuf[72];\n'
    '    sprintf(dbgBuf, ">> WriteData File02 (NDEF), fileLen=%u NLEN=%u", (unsigned)filePos, (unsigned)nlen);\n'
    '    logDebug(dbgBuf);\n'
    '    logToWeb("Schrijf NDEF URL naar kaart...", "info");\n'
    '\n'
    '    uint8_t response[16];\n'
    '    size_t responseLen = sizeof(response);\n'
    '    if (!sendCommand(cmd, cmdLen, response, responseLen)) {\n'
    '        logToWeb("NDEF URL schrijven mislukt", "error");\n'
    '        return false;\n'
    '    }\n'
    '    logDebug("<< NDEF write OK (SW=9100)");\n'
    '    logToWeb("NDEF URL geschreven", "success");\n'
    '    return true;\n'
    '}\n'
    '\n'
)

new_content = content[:start_idx] + new_func + content[end_idx:]
with open(path, 'w', encoding='utf-8') as f:
    f.write(new_content)
print('Done. Replaced %d chars with %d chars.' % (end_idx - start_idx, len(new_func)))
